Update Dory and R: add normalization

diff --git a/Dory b/Dory
--- a/Dory
+++ b/Dory
@@ -3,38 +3,69 @@
 usage() {
     echo "Usage:"
     echo "  Dory -m <FileFormat> -a <Input1> -b <Input2> -o <OutputPath> -c <ChrNum>   # For comparing two conditions"
-    echo "  Dory -m <FileFormat> -i <InputCoordFile> -l <LabelFile> -o <OutputPath> -n <LabelColname> -c <ChrNum>   # For comparing more than two conditions"
+    echo "  Dory -m <FileFormat> -i <InputCoordFile> -l <LabelFile> -o <OutputPath> -n <LabelColname> -c <ChrNum>    # For comparing more than two conditions"
     exit 1
 }
 
 output="."
 ctcolname="Cell_Type"
+norm=0
+nfa=""
+nfb=""
 # Parse arguments
 while [[ $# -gt 0 ]]; do
     case "$1" in
         -a) a_value="$2"; shift 2 ;;
         -b) b_value="$2"; shift 2 ;;
-        -i) i_value="$2"; mode="group"; shift 2 ;;  # If -i is present, switch to group mode
-        -l) l_value="$2"; mode="group"; shift 2 ;;  # If -l is present, switch to group mode
+        -i) i_value="$2"; shift 2 ;;  
+        -l) l_value="$2"; shift 2 ;;  
         -o) output="$2"; shift 2 ;;
         -m) file_format="$2"; shift 2 ;;
         -c) chr_format="$2"; shift 2 ;;
-        -n) ctcolname="$2"; mode="group"; shift 2 ;;
+        -n) ctcolname="$2"; shift 2 ;;
+        --norm) norm=1; shift ;;
+        --NormFactorA) nfa="$2"; shift 2 ;;
+        --NormFactorB) nfb="$2"; shift 2 ;;
+        --NormFactorI) nfi="$2"; shift 2 ;;
+        -h|--help) usage ;; 
         *) echo "Unknown parameter: $1"; usage ;;
     esac
 done
 
 mkdir -p "$output"
 
+
 SCRIPT_DIR="$(dirname "$(realpath "$0")")"
-# Call the appropriate R script
+
 if [[ -n "$a_value" && -n "$b_value" && -z "$i_value" && -z "$l_value" ]]; then
     # Run single mode
-    Rscript "$SCRIPT_DIR/R/Dory_single.R" -a "$a_value" -b "$b_value" -o "$output" -m "$file_format" -c "$chr_format"
+    if [[ -n "$nfa" && -z "$nfb" ]] || [[ -z "$nfa" && -n "$nfb" ]]; then
+        echo "Error: --NormFactorA and --NormFactorB must be provided together." >&2
+        exit 1
 
+    elif [[ "$norm" -eq 0  && -n "$nfa" && -n "$nfb" ]]; then
+        echo "Warning: --norm is required together with --NormFactorA and --NormFactorB. Providing only --NormFactorA and --NormFactorB is not sufficient, so basic mode will be run without normalization."
+        Rscript "$SCRIPT_DIR/R/Dory_single.R" -a "$a_value" -b "$b_value" -o "$output" -m "$file_format" -c "$chr_format" 
+    elif [[ "$norm" -eq 1 && -n "$nfa" && -n "$nfb" ]]; then    
+        Rscript "$SCRIPT_DIR/R/Dory_single_normfactor.R" -a "$a_value" -b "$b_value" -o "$output" -m "$file_format" -c "$chr_format" --NormFactorA "$nfa" --NormFactorB "$nfb"
+    elif [[  "$norm" -eq 1  && -z "$nfa" && -z "$nfb" ]]; then
+        Rscript "$SCRIPT_DIR/R/Dory_single_norm.R" -a "$a_value" -b "$b_value" -o "$output" -m "$file_format" -c "$chr_format" 
+    else 
+        Rscript "$SCRIPT_DIR/R/Dory_single.R" -a "$a_value" -b "$b_value" -o "$output" -m "$file_format" -c "$chr_format" 
+    fi 
+    
 elif [[ -n "$i_value" && -z "$a_value" && -z "$b_value" ]]; then
     # Run group mode 
-    Rscript "$SCRIPT_DIR/R/Dory_group.R" -i "$i_value" -l "$l_value" -n "$ctcolname" -o "$output" -m "$file_format" -c "$chr_format"
+    if [[ "$norm" -eq 0  && -n "$nfi" ]]; then
+        echo "Warning: --norm is required together with --NormFactorI. Providing only --NormFactorI is not sufficient, so basic mode will be run without normalization."
+        Rscript "$SCRIPT_DIR/R/Dory_group.R" -i "$i_value" -l "$l_value" -n "$ctcolname" -o "$output" -m "$file_format" -c "$chr_format" 
+    elif [[ "$norm" -eq 1 && -n "$nfi" ]]; then    
+         Rscript "$SCRIPT_DIR/R/Dory_group_normfactor.R" -i "$i_value" -l "$l_value" -n "$ctcolname" -o "$output" -m "$file_format" -c "$chr_format" --NormFactorI "$nfi"
+    elif [[  "$norm" -eq 1  && -z "$nfi" ]]; then
+        Rscript "$SCRIPT_DIR/R/Dory_group_norm.R" -i "$i_value" -l "$l_value" -n "$ctcolname" -o "$output" -m "$file_format" -c "$chr_format"  
+    else 
+        Rscript "$SCRIPT_DIR/R/Dory_group.R" -i "$i_value" -l "$l_value" -n "$ctcolname" -o "$output" -m "$file_format" -c "$chr_format" 
+    fi 
 
 else
     echo "Error: Invalid arguments. Use either:"
@@ -42,3 +73,5 @@ else
     echo "  -i <file> -l <file>  -m <format>     # For comparing a group of conditions"
     usage
 fi
+
+
